name: phpgdimageprocessing

# See: https://docs.devwithlando.io/config/proxy.html
proxy:
  appserver:
    - web.phpgdimageprocessing.lndo.site
  node:
    - node.phpgdimageprocessing.lndo.site
  mailhog:
    - mail.phpgdimageprocessing.lndo.site

# See: https://docs.devwithlando.io/config/services.html
services:
  appserver:
    webroot: public
    type: php:7.3
    via: apache:2.4
    ssl: false
    xdebug: true
    config:
      php: private/config/php/php.ini
    run_as_root:
      - "chown www-data: -R /app"
  node:
    type: node
    globals:
      npm: "latest"
      yarn: "latest"
      gulp-cli: "latest"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: 1026

# See: https://docs.devwithlando.io/config/tooling.html
tooling:
  node:
    service: node
  npm:
    service: node
  yarn:
    service: node
  gulp:
    service: node
  composer:
    service: appserver
  phpcs:
    service: appserver
    desription: "Analyze code against the PHP coding standards with PHP_CodeSniffer"
    cmd:
      - "vendor/bin/phpcs"
  phpcbf:
    service: appserver
    desription: "Fix coding standards warnings/errors automatically with PHP Code Beautifier"
    cmd:
      - "vendor/bin/phpcbf"
